### ISSUE TITLE
Document networkStatus

### ISSUE THREAD

**Issue by stubailo** [apollographql/react-docs#152]
This might be best done in a new page titled `Loading and error state` so it's easy to discover.

**Comment by helfer** [comment]
Any volunteers? 🙂

**Comment by rdickert** [comment]
This isn't documented in core-docs either. Wouldn't this belong there rather than (or in addition to) in the react docs? [Here's the source info](https://github.com/apollographql/apollo-client/blob/9e7c4d9e060928686896f7886e8266f1c27267c0/src/queries/networkStatus.ts) for anyone looking.

**Comment by helfer** [comment]
@rdickert I'd say let's put it in both places! 🙂

**Comment by DevanB** [comment]
I want to volunteer some of my time and help with documentation so there will be a few issues in this repo I'll be asking comments about prior to actually writing some docs. I want to make sure these aren't out-of-date issues before I start 😃

So I'm starting with this issue, because just a few weeks ago I was researching into `networkStatus` when looking to add `loading` to [ember-apollo-client](http://github.com/bgentry/ember-apollo-client).

Robert linked to the actual source file, which has (great) inline comments, but my question is should this page, "Loading and Error State", be added to the "Usage" section? I see some great documentation for all `loading`, `error`, and `networkStatus` in the "API Reference" area as well.

If this is the case (adding a page to the "Usage" section), I'll be glad to submit a PR and solicit feedback.

**Comment by stubailo** [comment]
Hmm, I think the documentation in the API section is decent: http://dev.apollodata.com/react/api-queries.html#graphql-query-data-networkStatus

Do you think it would be easier to find if it were under usage, or on a separate page?

Maybe it would be good to have a recipe page about managing loading status?

**Comment by DevanB** [comment]
I fully agree that the documentation in the API section is relatively thorough.

It also appears that the `loading` and `error` fields are mentioned in the [Queries] (http://dev.apollodata.com/react/queries.html#default-result-props) page in `data` prop explanation.

I'm not sure there is enough content to necessitate creating a page under the Usage section, but when phrased like "Managing Loading Status" it does seem more like a page for the Recipes section.

**Comment by theadactyl** [comment]
Closing this issue as docs code has moved to the following repositories:
- [graphql-tools](https://github.com/apollographql/graphql-tools/tree/master/docs)
- [apollo-server](https://github.com/apollographql/apollo-server/tree/master/docs)
- [subscriptions-transport-ws](https://github.com/apollographql/subscriptions-transport-ws/tree/master/docs)

And are live at apollographq.com here:
- [GraphQL Tools](https://www.apollographql.com/docs/graphql-tools/)
- [Apollo Server](https://www.apollographql.com/docs/apollo-server/)
- [Graphql Subscriptions](https://www.apollographql.com/docs/graphql-subscriptions/)

If this is still a problem in the new docs we'd appreciate you opening a new issue in the corresponding repo. Thanks! 🙏
