### ISSUE TITLE
Increase the number of items in the ToC

### ISSUE THREAD

**Issue by stubailo** [apollographql/react-docs#66]
For example, one should be "polling" rather than having to guess which part of the docs you want.

**Comment by helfer** [comment]
I just started doing this, but realized that the current structure is actually not so bad, because it puts the different alternatives next to each other, which may lead people to recognize that they should be using refetch when they wanted to look up polling.

If we want to do this, I think we should discuss the overall structure of the docs again, and figure out if there's another place for something that's more like a guide.

**Comment by stubailo** [comment]
I just think the titles are really vague - "controlling the store" doesn't really tell you anything. Perhaps we need some sort of "index" page that lists all of the different features one should know about.
